spring:
  application:
    name: stock-api-service
  #  cloud:
  #    kubernetes:
  #      discovery:
  #        all-namespaces: true
  webflux:
    base-path: /stock-api
caching:
  specs:
    allShares:
      timeout: 2500000 #1 day
    figis:
      timeout: 10
tinkoff:
  api:
    token: "t.txS1pNPoXBUtCrdlwiD9ZfBkmwhEBNOw-mWOAG-9STdFJPU4hHT-T72QBZ2NbetFnDeKOARLGDgp9kL53W_lAw"
