spring:
  application:
    name: stock-api-service
    cache:
      type: caffeine
      cache-names: [ 'exchanges' ]
      caffeine:
        spec: expireAfterWrite=1080m # 1 week
    cloud:
      kubernetes:
        discovery:
          all-namespaces: true
  webflux:
    base-path: /stock-api
#reactive:
#  feign:
#    client:
#      config:
#        default:
#          connectTimeout: 2500000
#          readTimeout: 2500000
feign-services:
  moex-stock-api-endpoint: ""
  yahoo-stock-api-endpoint: ""
server:
  port: 8080
logging:
  level:
    reactivefeign.client.log: DEBUG
